default:
  image:
    archlinux:latest

build:
  tags:
    - medium

  script:
    - pacman --noconfirm --needed -Syu base-devel gnupg git
    - ls
    - useradd -m build
    - ls ..
    - echo 'build ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers
    - cp -r ../repos-test /home/build/
    - cd /home/build/repos-test
    - echo $GPG_PRIV_KEY | base64 -d > ../key.asc
    - chown -R build:build ../repos-test
    - su -c "bash -c 'cd repo/pod2man && makepkg -i --noconfirm'" build
    - su -c 'gpg --import ../key.asc' build
    - su -c 'BUILD_ONLY='' ./pkgbuild.sh' build
    - su -m -c './ci-upload.sh' build