default:
  tags:
    - medium
  image:
    archlinux:latest

stages:
  - build
  - post

build:
  stage: build

  artifacts:
    untracked: true
    expire_in: 1 day
  only:
    changes:
      - repo/**/*

  script:
    - pacman --noconfirm --needed -Syu base-devel gnupg git
    - git submodule update --init
    - useradd -m build
    - echo 'build ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers
    #- cp -r ../$CI_PROJECT_TITLE  /home/build/
    #- cd /home/build/$CI_PROJECT_TITLE
    - chown -R build:build ../$CI_PROJECT_TITLE 
    - su -c "bash -c 'cd repo/pod2man && makepkg -i --noconfirm'" build
    - su -c "bash -c 'cd repo/gconf && makepkg -i --noconfirm'" build
    - su -c 'echo $GPG_PRIV_KEY | base64 -d | gpg --import' build
    - su -c 'BUILD_ONLY='' ./pkgbuild.sh' build
    - rm -rf build/

# only push to master master trigger push
post:
  stage: post

  only:
    refs:
      - master
    changes:
      - repo/**/*

  script:
    - if [ -n "$TARGET_HOSTS" ]; then echo "$TARGET_HOSTS" | base64 -d >> /etc/hosts; fi;
    - bash -c './ci-upload.sh'
