default:
  tags:
    - medium
  image:
    archlinux:latest

stages:
  - build
  - post

build:
  stage: build

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  artifacts:
    paths:
      - packages/
      - .fail
    expire_in: 4 hours
  only:
    changes:
      - .gitlab-ci.yml
      - utils/pkgbuild.sh
      - repo/**/*
      - makepkg.d/*

  script:
    #- echo -e '\n[archlinuxcn]\nServer = https://repo.archlinuxcn.org/$arch\n' >> /etc/pacman.conf
    - bash -c "echo -e '\n[kunoisayami]\nServer = https://$REPO_REMOTE/\$arch\n' >> /etc/pacman.conf"
    - pacman-key --init
    # import myself key first
    - curl -fL https://keys.openpgp.org/vks/v1/by-fingerprint/4A0F0C8BC709ACA4341767FB243975C8DB9656B9 | pacman-key --add -
    - pacman-key --finger 4A0F0C8BC709ACA4341767FB243975C8DB9656B9
    - pacman-key --lsign-key 4A0F0C8BC709ACA4341767FB243975C8DB9656B9
    - pacman --noconfirm --needed -Syu base-devel gnupg git yay pcre
    - useradd -m build
    - echo 'build ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers
    #- cp -r ../$CI_PROJECT_TITLE  /home/build/
    #- cd /home/build/$CI_PROJECT_TITLE
    - chown -R build:build ../$CI_PROJECT_TITLE
    - su -c './utils/pkgbuild_bootstrap' build
    - "rm -rf build/ || true"
