default:
  image:
    archlinux:latest

build:
  tags:
    - medium

  only:
    changes:
      - repo/**/*

  script:
    - pacman --noconfirm --needed -Syu base-devel gnupg git
    - useradd -m build
    - echo 'build ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers
    - cp -r ../$CI_PROJECT_TITLE  /home/build/
    - cd /home/build/$CI_PROJECT_TITLE
    - echo $GPG_PRIV_KEY | base64 -d > ../key.asc
    - chown -R build:build ../$CI_PROJECT_TITLE
    - su -c "bash -c 'cd repo/pod2man && makepkg -i --noconfirm'" build
    - su -c 'gpg --import ../key.asc' build
    - su -c 'BUILD_ONLY='' ./pkgbuild.sh' build
    - su -m -c './ci-upload.sh' build
