name: Check aur updates

on:
  schedule:
    - cron: '19,49 * * * *'

jobs:
  check-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    name: Build
    steps:
      - name: Set up base image
        uses: 67au/check-aur-update-github-action@v0.1.0
      - name: Initialize submodules
        shell: bash
        run: |
          git submodule update --init
      - name: Check updates
        shell: bash
        run: |
          ./utils/aur/check-aur-update.py --parse-pkgbuild ./utils/parse-pkgbuild.sh repo
      - name: Set environments
        id: get_env
        shell: bash
        run: |
          echo "::set-output name=date::$(date +%Y%m%d%H%M)"
          echo "::set-output name=body::$(git diff --name-only | sed -e 's|^repo/|* |')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: 'Auto update aur repository ${{ steps.get_env.outputs.date }}'
          title: Update aur repository
          delete-branch: true
          branch: update/aur-${{ steps.get_env.outputs.date }}
          body: "Update packages:\n${{ steps.get_env.outputs.body }}"
